export const usCities = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Houston, TX",
    "Phoenix, AZ",
    "Philadelphia, PA",
    "San Antonio, TX",
    "San Diego, CA",
    "Dallas, TX",
    "San Jose, CA",
    "Austin, TX",
    "Jacksonville, FL",
    "Fort Worth, TX",
    "Columbus, OH",
    "Charlotte, NC",
    "San Francisco, CA",
    "Indianapolis, IN",
    "Seattle, WA",
    "Denver, CO",
    "Boston, MA",
    "El Paso, TX",
    "Detroit, MI",
    "Nashville, TN",
    "Portland, OR",
    "Memphis, TN",
    "Oklahoma City, OK",
    "Las Vegas, NV",
    "Louisville, KY",
    "Baltimore, MD",
    "Milwaukee, WI",
    "Albuquerque, NM",
    "Tucson, AZ",
    "Fresno, CA",
    "Sacramento, CA",
    "Atlanta, GA",
    "Kansas City, MO",
    "Miami, FL",
    "Raleigh, NC",
    "Omaha, NE",
    "Minneapolis, MN",
    "Cleveland, OH",
    "Tulsa, OK",
    "Oakland, CA",
    "Tampa, FL",
    "Arlington, TX",
    "New Orleans, LA",
    "Wichita, KS",
    "Bakersfield, CA",
    "Aurora, CO",
    "Anaheim, CA",
    // Add hundreds more cities here...
  ];